apiVersion: apps/v1
kind: Deployment
metadata:
  name: bing-cloud-app
  labels:
    app: bing-cloud-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bing-cloud-app
  template:
    metadata:
      labels:
        app: bing-cloud-app
    spec:
      containers:
        - name: bing-cloud-app
          image: szsong100/bingo-app:{{IMAGE_TAG}}
          ports:
          - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
