apiVersion: v1
kind: Service
metadata:
  name: bing-cloud-app-service
spec:
  type: NodePort
  selector:
    app: bing-cloud-app-service
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
